I can see the remaining N/A addresses from your data. Let's update the formula to handle these specific cases. **

**Enhanced County_State_Added formula with all missing municipalities:**

```m
= Table.AddColumn(MatchCity, "County_State", each 
    if [matched_municipality] <> null then 
        // Bergen County, NJ
        if [matched_municipality] = "hackensack" then "Bergen, NJ"
        else if [matched_municipality] = "hacknesack" then "Bergen, NJ"
        else if [matched_municipality] = "teaneck" then "Bergen, NJ"
        else if [matched_municipality] = "ridgefield park" then "Bergen, NJ"
        else if [matched_municipality] = "east rutherford" then "Bergen, NJ"
        else if [matched_municipality] = "moonachie" then "Bergen, NJ"
        else if [matched_municipality] = "fort lee" then "Bergen, NJ"
        else if [matched_municipality] = "rochelle park" then "Bergen, NJ"
        else if [matched_municipality] = "garfield" then "Bergen, NJ"
        else if [matched_municipality] = "hasbrouck heights" then "Bergen, NJ"
        else if [matched_municipality] = "wood ridge" then "Bergen, NJ"
        
        // Essex County, NJ
        else if [matched_municipality] = "newark" then "Essex, NJ"
        else if [matched_municipality] = "east orange" then "Essex, NJ"
        
        // Passaic County, NJ
        else if [matched_municipality] = "paterson" then "Passaic, NJ"
        
        // Warren County, NJ
        else if [matched_municipality] = "phillipsburg" then "Warren, NJ"
        
        // Camden County, NJ
        else if [matched_municipality] = "camden" then "Camden, NJ"
        
        // Somerset County, NJ
        else if [matched_municipality] = "raritan" then "Somerset, NJ"
        
        // New York Counties
        else if [matched_municipality] = "manhattan" then "New York, NY"
        else if [matched_municipality] = "york" then "New York, NY"
        else if [matched_municipality] = "bronx" then "Bronx, NY"
        else if [matched_municipality] = "staten island" then "Richmond, NY"
        else if [matched_municipality] = "spring valley" then "Rockland, NY"
        
        // Pennsylvania Counties
        else if [matched_municipality] = "reading" then "Berks, PA"
        else if [matched_municipality] = "chambersburg" then "Franklin, PA"
        
        else "Unmatched"
    else if Text.Contains(Text.Lower([address] ? ? ""), "homeless") then "Bergen, NJ"
    else "N/A", type text)
```

**New Additions Based on Your Data:**
- ✅ **Wood Ridge** → Bergen, NJ  
- ✅ **Reading, PA** → Berks, PA
- ✅ **Chambersburg, PA** → Franklin, PA
- ✅ **Homeless handling** → Bergen, NJ

**This should eliminate nearly all N/A values** except for:
- Completely missing/null addresses
- Severely malformed addresses that can't be parsed

**Apply this enhanced formula and your N/A count should drop to near zero! **



## Prompt:
6/13/2025, 5:28:56 PM

!