Burglaries to Commercial and Residential Locations
Type of Structure (Single-Family Home, Apartment, Business, Warehouse, Storage Unit)
Method of Entry (Unlocked, Forced Entry, Roof Entry, Window Break, Keyed Entry)
Time of Occurrence (Daytime, Nighttime, Unoccupied vs. Occupied)
Property Stolen (Cash, Jewelry, Electronics, Firearms, Drugs, Tools, Identity Documents)
Security Measures Present (Alarm, CCTV, Lighting, Door Locks, Bars, Safe)
Repeat Victimization (Prior Incidents, Same Method)
Suspect Information (Individual, Organized Crew, Transient Offender)
Point of Entry & Exit
Prompt:
7-Day:
You are an Excel and Power Query expert. I want to update the M Code for the below source query so only records that with an INC_DATE that fall in the current 7_Day cycle minus 1 day appear. Example today is April 15, 2025, I would want the records with INC_DATE of 04/08/25 to 04/14/25 shown. 28-Day:
You are an Excel and Power Query expert. I want to update the M Code for the below source query so only records that with an INC_DATE that fall in the current 28_Day cycle minus 1 day appear. Example today is April 15, 2025, I would want the records with INC_DATE of 03/18/25 to 04/14/25 shown. Action:
Provide the M Code for both the 7_Day and 28_day
Source Query: Bur_C_R_7D 
 Source M Code:
let Source = Folder.Files("C:\Users\carucci_r\OneDrive - City of Hackensack_LawSoft_EXPORT\RMS\EXPORT_RMS"), #"Filtered Hidden Files1" = Table.SelectRows(Source, each [Attributes]?[Hidden]? <> true), #"Invoke Custom Function1" = Table.AddColumn(#"Filtered Hidden Files1", "Transform File", each #"Transform File"([Content])), #"Renamed Columns1" = Table.RenameColumns(#"Invoke Custom Function1", {"Name", "Source.Name"}), #"Removed Other Columns1" = Table.SelectColumns(#"Renamed Columns1", {"Source.Name", "Transform File"}), #"Expanded Table Column1" = Table.ExpandTableColumn(#"Removed Other Columns1", "Transform File", Table.ColumnNames(#"Transform File"(#"Sample File"))), #"Changed Type" = Table.TransformColumnTypes(#"Expanded Table Column1",{{"Source.Name", type text}, {"Case Number", type text}, {"Incident Date", type date}, {"Incident Time", type datetime}, {"Incident Date_Between", type date}, {"Incident Time_Between", type datetime}, {"Report Date", type date}, {"Report Time", type datetime}, {"Incident Type_1", type text}, {"Incident Type_2", type text}, {"Incident Type_3", type text}, {"FullAddress", type text}, {"Grid", type text}, {"Zone", Int64.Type}, {"Narrative", type text}, {"Total Value Stolen", type any}, {"Total Value Recover", type any}, {"Registration 1", type text}, {"Make1", type text}, {"Model1", type text}, {"Reg State 1", type text}, {"Registration 2", type any}, {"Reg State 2", type any}, {"Make2", type any}, {"Model2", type any}, {"Reviewed By", type text}, {"CompleteCalc", type text}, {"Officer of Record", type text}, {"Squad", type text}, {"Det_Assigned", type text}, {"Case_Status", type text}, {"NIBRS Classification", type text}}), #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Source.Name"}), #"Changed Type1" = Table.TransformColumnTypes(#"Removed Columns",{{"Start of Hour", type time}, {"INC_TIME", type time}, {"INC_DATE", type date}, {"Total Value Stolen", Currency.Type}, {"Total Value Recover", Currency.Type}, {"INC_DATE_AND_TIME", type datetime}}), #"Filtered Rows" = Table.SelectRows(#"Changed Type1", each Text.Contains([ALL_INCIDENTS], "Commercial") or Text.Contains([ALL_INCIDENTS], "Residence")), #"Removed Duplicates" = Table.Distinct(#"Filtered Rows", {"Case Number"}), #"Reordered Columns" = Table.ReorderColumns(#"Removed Duplicates",{"Case Number", "INC_DATE", "TOD", "Start of Hour", "INC_TIME", "Day Name", "Month Name", "BLOCK", "Location", "ALL_INCIDENTS", "Incident Type_1", "Incident Type_2", "Incident Type_3", "FullAddress", "Grid", "Zone", "Narrative", "Total Value Stolen", "Total Value Recover", "Registration 1", "Make1", "Model1", "Reg State 1", "Registration 2", "Reg State 2", "Make2", "Model2", "Reviewed By", "CompleteCalc", "Officer of Record", "Squad", "Det_Assigned", "Case_Status", "NIBRS Classification", "CASE_NUMBER_LENGTH", "Incident Date", "Incident Time", "Incident Date_Between", "Incident Time_Between", "Report Date", "Report Time", "Year", "Week of Year", "Week of Month", "Day", "Day of Year", "INC_DATE_AND_TIME", "St#", "Notes", "VEHICLE", "Suspect", "TOTAL_STOLEN_AMOUNT", "REPORT_CYCLE", "TIME_OF_DAY"}), #"Changed Type2" = Table.TransformColumnTypes(#"Reordered Columns",{{"Report Time", type time}, {"Incident Time_Between", type time}, {"Incident Time", type time}}), #"Filtered Rows1" = Table.SelectRows(#"Changed Type2", each ([Incident Type_3] <> "Domestic Violence") and ([Incident Type_1] <> "Violation of Court Order") and ([Case Number] <> "25-021703")), #"Reordered Columns1" = Table.ReorderColumns(#"Filtered Rows1",{"BLOCK", "Case Number", "INC_DATE", "TOD", "Start of Hour", "INC_TIME", "Day Name", "Month Name", "Location", "ALL_INCIDENTS", "Incident Type_1", "Incident Type_2", "Incident Type_3", "FullAddress", "Grid", "Zone", "Narrative", "Total Value Stolen", "Total Value Recover", "Registration 1", "Make1", "Model1", "Reg State 1", "Registration 2", "Reg State 2", "Make2", "Model2", "Reviewed By", "CompleteCalc", "Officer of Record", "Squad", "Det_Assigned", "Case_Status", "NIBRS Classification", "CASE_NUMBER_LENGTH", "Incident Date", "Incident Time", "Incident Date_Between", "Incident Time_Between", "Report Date", "Report Time", "Year", "Week of Year", "Week of Month", "Day", "Day of Year", "INC_DATE_AND_TIME", "St#", "Notes", "VEHICLE", "Suspect", "TOTAL_STOLEN_AMOUNT", "REPORT_CYCLE", "TIME_OF_DAY"}), #"Removed Columns1" = Table.RemoveColumns(#"Reordered Columns1",{"Case Number"}), #"Reordered Columns2" = Table.ReorderColumns(#"Removed Columns1",{"BLOCK", "INC_DATE", "Day Name", "TOD", "Start of Hour", "INC_TIME", "Month Name", "Location", "ALL_INCIDENTS", "Incident Type_1", "Incident Type_2", "Incident Type_3", "FullAddress", "Grid", "Zone", "Narrative", "Total Value Stolen", "Total Value Recover", "Registration 1", "Make1", "Model1", "Reg State 1", "Registration 2", "Reg State 2", "Make2", "Model2", "Reviewed By", "CompleteCalc", "Officer of Record", "Squad", "Det_Assigned", "Case_Status", "NIBRS Classification", "CASE_NUMBER_LENGTH", "Incident Date", "Incident Time", "Incident Date_Between", "Incident Time_Between", "Report Date", "Report Time", "Year", "Week of Year", "Week of Month", "Day", "Day of Year", "INC_DATE_AND_TIME", "St#", "Notes", "VEHICLE", "Suspect", "TOTAL_STOLEN_AMOUNT", "REPORT_CYCLE", "TIME_OF_DAY"}), #"Renamed Columns" = Table.RenameColumns(#"Reordered Columns2",{{"Day Name", "Day of Week"}, {"BLOCK", "Blocj"}}), #"Removed Columns2" = Table.RemoveColumns(#"Renamed Columns",{"CASE_NUMBER_LENGTH", "Incident Date", "Incident Time", "Incident Date_Between", "Incident Time_Between", "Report Date", "Report Time"}), #"Renamed Columns2" = Table.RenameColumns(#"Removed Columns2",{{"INC_DATE", "Incident Date"}, {"TOD", "Time of Day"}}), #"Removed Columns3" = Table.RemoveColumns(#"Renamed Columns2",{"Start of Hour", "INC_TIME", "Month Name", "Location", "ALL_INCIDENTS", "Incident Type_1", "Incident Type_2", "Incident Type_3", "FullAddress", "Grid", "Zone", "Total Value Stolen", "Total Value Recover", "Registration 1", "Make1", "Model1", "Reg State 1", "Registration 2", "Reg State 2", "Make2", "Model2", "Reviewed By", "CompleteCalc", "Officer of Record", "Squad", "Det_Assigned", "Case_Status", "NIBRS Classification", "Year", "Week of Year", "Week of Month", "Day", "Day of Year", "INC_DATE_AND_TIME", "St#", "Narrative"}), #"Reordered Columns3" = Table.ReorderColumns(#"Removed Columns3",{"TIME_OF_DAY", "Blocj", "Incident Date", "Day of Week", "Time of Day", "VEHICLE", "Suspect", "TOTAL_STOLEN_AMOUNT", "REPORT_CYCLE", "Notes"}), #"Removed Columns4" = Table.RemoveColumns(#"Reordered Columns3",{"Time of Day"}), #"Reordered Columns4" = Table.ReorderColumns(#"Removed Columns4",{"Blocj", "Incident Date", "Day of Week", "TIME_OF_DAY", "VEHICLE", "Suspect", "TOTAL_STOLEN_AMOUNT", "REPORT_CYCLE", "Notes"}), #"Renamed Columns3" = Table.RenameColumns(#"Reordered Columns4",{{"TIME_OF_DAY", "Time of Day"}, {"VEHICLE", "Involved Vehicle"}}), #"Reordered Columns5" = Table.ReorderColumns(#"Renamed Columns3",{"Blocj", "Incident Date", "Day of Week", "Time of Day", "Suspect", "Involved Vehicle", "TOTAL_STOLEN_AMOUNT", "REPORT_CYCLE", "Notes"}), #"Type of Structure" = Table.AddColumn(#"Reordered Columns5", "Type of Structure", each null), #"Method of Entry" = Table.AddColumn(#"Type of Structure", "Method of Entry", each null), #"Renamed Columns4" = Table.RenameColumns(#"Method of Entry",{{"Blocj", "Block"}}), #"Removed Columns5" = Table.RemoveColumns(#"Renamed Columns4",{"REPORT_CYCLE"}), #"Reordered Columns6" = Table.ReorderColumns(#"Removed Columns5",{"Block", "Incident Date", "Day of Week", "Time of Day", "Suspect", "Involved Vehicle", "Method of Entry", "Type of Structure", "TOTAL_STOLEN_AMOUNT", "Notes"}), #"Renamed Columns5" = Table.RenameColumns(#"Reordered Columns6",{{"TOTAL_STOLEN_AMOUNT", "Property Stolen"}}), #"Security Measures Present" = Table.AddColumn(#"Renamed Columns5", "Security Measures Present", each null), #"Reordered Columns7" = Table.ReorderColumns(#"Security Measures Present",{"Block", "Incident Date", "Day of Week", "Time of Day", "Suspect", "Involved Vehicle", "Method of Entry", "Type of Structure", "Property Stolen", "Security Measures Present", "Notes"}), #"Point of Entry" = Table.AddColumn(#"Reordered Columns7", "Point of Entry", each null), #"Point of Exit" = Table.AddColumn(#"Point of Entry", "Point of Exit", each null), #"Reordered Columns8" = Table.ReorderColumns(#"Point of Exit",{"Block", "Incident Date", "Day of Week", "Time of Day", "Suspect", "Involved Vehicle", "Method of Entry", "Point of Entry", "Point of Exit", "Type of Structure", "Property Stolen", "Security Measures Present", "Notes"}) in #"Reordered Columns8"
Helper Query: 7Day_28Day_250414 
Helper Query Content:
Report_Due_Date 7_Day_Start 7_Day_End 28_Day_Start 28_Day_End Report_Name Is_Due 01/07/25 12/31/24 01/06/25 12/10/24 01/06/25 C01W01 FALSE 01/14/25 01/07/25 01/13/25 12/17/24 01/13/25 C01W02 FALSE 01/21/25 01/14/25 01/20/25 12/24/24 01/20/25 C01W03 FALSE 01/28/25 01/21/25 01/27/25 12/31/24 01/27/25 C01W04 FALSE 02/04/25 01/28/25 02/03/25 01/07/25 02/03/25 C02W05 FALSE 02/11/25 02/04/25 02/10/25 01/14/25 02/10/25 C02W06 FALSE 02/18/25 02/11/25 02/17/25 01/21/25 02/17/25 C02W07 FALSE 02/25/25 02/18/25 02/24/25 01/28/25 02/24/25 C02W08 FALSE 03/04/25 02/25/25 03/03/25 02/04/25 03/03/25 C03W09 FALSE 03/11/25 03/04/25 03/10/25 02/11/25 03/10/25 C03W10 FALSE 03/18/25 03/11/25 03/17/25 02/18/25 03/17/25 C03W11 FALSE 03/25/25 03/18/25 03/24/25 02/25/25 03/24/25 C03W12 FALSE 04/01/25 03/25/25 03/31/25 03/04/25 03/31/25 C04W13 FALSE 04/08/25 04/01/25 04/07/25 03/11/25 04/07/25 C04W14 FALSE 04/15/25 04/08/25 04/14/25 03/18/25 04/14/25 C04W15 FALSE 04/22/25 04/15/25 04/21/25 03/25/25 04/21/25 C04W16 TRUE 04/29/25 04/22/25 04/28/25 04/01/25 04/28/25 C05W17 FALSE 05/06/25 04/29/25 05/05/25 04/08/25 05/05/25 C05W18 FALSE 05/13/25 05/06/25 05/12/25 04/15/25 05/12/25 C05W19 FALSE 05/20/25 05/13/25 05/19/25 04/22/25 05/19/25 C05W20 FALSE 05/27/25 05/20/25 05/26/25 04/29/25 05/26/25 C06W21 FALSE 06/03/25 05/27/25 06/02/25 05/06/25 06/02/25 C06W22 FALSE 06/10/25 06/03/25 06/09/25 05/13/25 06/09/25 C06W23 FALSE 06/17/25 06/10/25 06/16/25 05/20/25 06/16/25 C06W24 FALSE 06/24/25 06/17/25 06/23/25 05/27/25 06/23/25 C07W25 FALSE 07/01/25 06/24/25 06/30/25 06/03/25 06/30/25 C07W26 FALSE 07/08/25 07/01/25 07/07/25 06/10/25 07/07/25 C07W27 FALSE 07/15/25 07/08/25 07/14/25 06/17/25 07/14/25 C07W28 FALSE 07/22/25 07/15/25 07/21/25 06/24/25 07/21/25 C08W29 FALSE 07/29/25 07/22/25 07/28/25 07/01/25 07/28/25 C08W30 FALSE 08/05/25 07/29/25 08/04/25 07/08/25 08/04/25 C08W31 FALSE 08/12/25 08/05/25 08/11/25 07/15/25 08/11/25 C08W32 FALSE 08/19/25 08/12/25 08/18/25 07/22/25 08/18/25 C09W33 FALSE 08/26/25 08/19/25 08/25/25 07/29/25 08/25/25 C09W34 FALSE 09/02/25 08/26/25 09/01/25 08/05/25 09/01/25 C09W35 FALSE 09/09/25 09/02/25 09/08/25 08/12/25 09/08/25 C09W36 FALSE 09/16/25 09/09/25 09/15/25 08/19/25 09/15/25 C10W37 FALSE 09/23/25 09/16/25 09/22/25 08/26/25 09/22/25 C10W38 FALSE 09/30/25 09/23/25 09/29/25 09/02/25 09/29/25 C10W39 FALSE 10/07/25 09/30/25 10/06/25 09/09/25 10/06/25 C10W40 FALSE 10/14/25 10/07/25 10/13/25 09/16/25 10/13/25 C11W41 FALSE 10/21/25 10/14/25 10/20/25 09/23/25 10/20/25 C11W42 FALSE 10/28/25 10/21/25 10/27/25 09/30/25 10/27/25 C11W43 FALSE 11/04/25 10/28/25 11/03/25 10/07/25 11/03/25 C11W44 FALSE 11/11/25 11/04/25 11/10/25 10/14/25 11/10/25 C12W45 FALSE 11/18/25 11/11/25 11/17/25 10/21/25 11/17/25 C12W46 FALSE 11/25/25 11/18/25 11/24/25 10/28/25 11/24/25 C12W47 FALSE 12/02/25 11/25/25 12/01/25 11/04/25 12/01/25 C12W48 FALSE 12/09/25 12/02/25 12/08/25 11/11/25 12/08/25 C13W49 FALSE 12/16/25 12/09/25 12/15/25 11/18/25 12/15/25 C13W50 FALSE 12/23/25 12/16/25 12/22/25 11/25/25 12/22/25 C13W51 FALSE 12/30/25 12/23/25 12/29/25 12/02/25 12/29/25 C13W52 FALSE