let

  Source = Csv.Document(
    File.Contents(
      "CHANGE PATH HERE\Power Query - Clean Trim.csv"
    ), [Delimiter = ",", Columns = 8, Encoding = 1252, QuoteStyle = QuoteStyle.Csv] ),

  // Promote the first row to a header row
  #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),

  // Convert all columns to text format
  ConvertAllToText = Table.TransformColumns(#"Promoted Headers", {}, Text.From),

  // Clean all text columns
  CleanAllTextColumns = Table.TransformColumns(ConvertAllToText, {}, Text.Clean),

  // Trim whitespace from all text columns
  TrimAllTextColumns = Table.TransformColumns(CleanAllTextColumns, {}, Text.Trim),

  // Set all columns to their proper data types
  SetDataTypes = Table.TransformColumnTypes(
    TrimAllTextColumns,
    { {"Date", type date},
      {"SalesRep", type text},
      {"Product", type text},
      {"Ship To", type text},
      {"Region", type text},
      {"Purchaser", type text},
      {"Cost", Int64.Type},
      {"Sales", Int64.Type} } )

in

  SetDataTypes