let Source = Excel.Workbook(Parameter1, null, true), Sheet1_Sheet = Source{[Item="Sheet1",Kind="Sheet"]}[Data], #"Promoted Headers" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true]), #"Added Custom" = Table.AddColumn(#"Promoted Headers", "CASE_NUMBER_LENGTH", each Text.Length([Case Number])), #"Filtered Rows" = Table.SelectRows(#"Added Custom", each [CASE_NUMBER_LENGTH] = 9), #"Changed Type" = Table.TransformColumnTypes(#"Filtered Rows",{{"Incident Date", type date}, {"Incident Date_Between", type date}, {"Report Date", type date}, {"Report Time", type time}, {"Incident Time_Between", type time}, {"Incident Time", type time}}), #"Reordered Columns" = Table.ReorderColumns(#"Changed Type",{"Case Number", "Incident Type_1", "Incident Type_2", "Incident Type_3", "FullAddress", "Grid", "Zone", "Narrative", "Total Value Stolen", "Total Value Recover", "Registration 1", "Make1", "Model1", "Reg State 1", "Registration 2", "Reg State 2", "Make2", "Model2", "Reviewed By", "CompleteCalc", "Officer of Record", "Squad", "Det_Assigned", "Case_Status", "NIBRS Classification", "CASE_NUMBER_LENGTH", "Incident Date", "Incident Time", "Incident Date_Between", "Incident Time_Between", "Report Date", "Report Time"}), #"Added Custom1" = Table.AddColumn(#"Reordered Columns", "INC_DATE", each if [Incident Date] = null then (if [Incident Date_Between] = null then [Report Date] else [Incident Date_Between]) else [Incident Date]), #"Added Custom2" = Table.AddColumn(#"Added Custom1", "INC_TIME", each if [Incident Time] = null then (if [Incident Time_Between] = null then [Report Time] else [Incident Time_Between]) else [Incident Time]), #"Changed Type1" = Table.TransformColumnTypes(#"Added Custom2",{{"INC_DATE", type date}, {"INC_TIME", type time}}), #"Inserted Start of Hour" = Table.AddColumn(#"Changed Type1", "Start of Hour", each Time.StartOfHour([INC_TIME]), type time), #"Inserted Year" = Table.AddColumn(#"Inserted Start of Hour", "Year", each Date.Year([INC_DATE]), Int64.Type), #"Reordered Columns1" = Table.ReorderColumns(#"Inserted Year",{"Case Number", "Incident Type_1", "Incident Type_2", "Incident Type_3", "FullAddress", "Grid", "Zone", "Narrative", "Total Value Stolen", "Total Value Recover", "Registration 1", "Make1", "Model1", "Reg State 1", "Registration 2", "Reg State 2", "Make2", "Model2", "Reviewed By", "CompleteCalc", "Officer of Record", "Squad", "Det_Assigned", "Case_Status", "NIBRS Classification", "CASE_NUMBER_LENGTH", "Incident Date", "Incident Time", "Incident Date_Between", "Incident Time_Between", "Report Date", "Report Time", "INC_DATE", "Year", "INC_TIME", "Start of Hour"}), #"Inserted Month Name" = Table.AddColumn(#"Reordered Columns1", "Month Name", each Date.MonthName([INC_DATE]), type text), #"Inserted Week of Year" = Table.AddColumn(#"Inserted Month Name", "Week of Year", each Date.WeekOfYear([INC_DATE]), Int64.Type), #"Inserted Week of Month" = Table.AddColumn(#"Inserted Week of Year", "Week of Month", each Date.WeekOfMonth([INC_DATE]), Int64.Type), #"Inserted Day" = Table.AddColumn(#"Inserted Week of Month", "Day", each Date.Day([INC_DATE]), Int64.Type), #"Inserted Day of Year" = Table.AddColumn(#"Inserted Day", "Day of Year", each Date.DayOfYear([INC_DATE]), Int64.Type), #"Inserted Day Name" = Table.AddColumn(#"Inserted Day of Year", "Day Name", each Date.DayOfWeekName([INC_DATE]), type text), #"Inserted Merged Column" = Table.AddColumn(#"Inserted Day Name", "INC_DATE_AND_TIME", each Text.Combine({Text.From([INC_DATE], "en-US"), Text.From([INC_TIME], "en-US")}, " "), type text), #"Reordered Columns2" = Table.ReorderColumns(#"Inserted Merged Column",{"Case Number", "INC_DATE", "Month Name", "Day Name", "INC_TIME", "Incident Type_1", "Incident Type_2", "Incident Type_3", "FullAddress", "Grid", "Zone", "Narrative", "Total Value Stolen", "Total Value Recover", "Registration 1", "Make1", "Model1", "Reg State 1", "Registration 2", "Reg State 2", "Make2", "Model2", "Reviewed By", "CompleteCalc", "Officer of Record", "Squad", "Det_Assigned", "Case_Status", "NIBRS Classification", "CASE_NUMBER_LENGTH", "Incident Date", "Incident Time", "Incident Date_Between", "Incident Time_Between", "Report Date", "Report Time", "Year", "Start of Hour", "Week of Year", "Week of Month", "Day", "Day of Year", "INC_DATE_AND_TIME"}), #"Changed Type2" = Table.TransformColumnTypes(#"Reordered Columns2",{{"INC_DATE_AND_TIME", type datetime}}), #"Reordered Columns3" = Table.ReorderColumns(#"Changed Type2",{"Case Number", "INC_DATE", "Month Name", "Day Name", "INC_TIME", "Start of Hour", "Incident Type_1", "Incident Type_2", "Incident Type_3", "FullAddress", "Grid", "Zone", "Narrative", "Total Value Stolen", "Total Value Recover", "Registration 1", "Make1", "Model1", "Reg State 1", "Registration 2", "Reg State 2", "Make2", "Model2", "Reviewed By", "CompleteCalc", "Officer of Record", "Squad", "Det_Assigned", "Case_Status", "NIBRS Classification", "CASE_NUMBER_LENGTH", "Incident Date", "Incident Time", "Incident Date_Between", "Incident Time_Between", "Report Date", "Report Time", "Year", "Week of Year", "Week of Month", "Day", "Day of Year", "INC_DATE_AND_TIME"}), #"Extracted Text Before Delimiter" = Table.TransformColumns(#"Reordered Columns3", {{"Incident Type_1", each Text.BeforeDelimiter(, " - 2C:"), type text}, {"Incident Type_2", each Text.BeforeDelimiter(, " - 2C:"), type text}, {"Incident Type_3", each Text.BeforeDelimiter(_, " - 2C:"), type text}}), #"Added Custom3" = Table.AddColumn(#"Extracted Text Before Delimiter", "ALL_INCIDENTS", each Text.Combine(List.Select({[Incident Type_1], [Incident Type_2], [Incident Type_3]}, each _ <> null and _ <> ""), ", ")), #"Reordered Columns4" = Table.ReorderColumns(#"Added Custom3",{"Case Number", "INC_DATE", "Month Name", "Day Name", "INC_TIME", "Start of Hour", "Incident Type_1", "ALL_INCIDENTS", "Incident Type_2", "Incident Type_3", "FullAddress", "Grid", "Zone", "Narrative", "Total Value Stolen", "Total Value Recover", "Registration 1", "Make1", "Model1", "Reg State 1", "Registration 2", "Reg State 2", "Make2", "Model2", "Reviewed By", "CompleteCalc", "Officer of Record", "Squad", "Det_Assigned", "Case_Status", "NIBRS Classification", "CASE_NUMBER_LENGTH", "Incident Date", "Incident Time", "Incident Date_Between", "Incident Time_Between", "Report Date", "Report Time", "Year", "Week of Year", "Week of Month", "Day", "Day of Year", "INC_DATE_AND_TIME"}), #"Trimmed Text" = Table.TransformColumns(#"Reordered Columns4",{{"FullAddress", Text.Trim, type text}}), #"Cleaned Text" = Table.TransformColumns(#"Trimmed Text",{{"FullAddress", Text.Clean, type text}}), #"Inserted Text Before Delimiter" = Table.AddColumn(#"Cleaned Text", "Text Before Delimiter", each Text.BeforeDelimiter([FullAddress], ", "), type text), #"Inserted Text Before Delimiter1" = Table.AddColumn(#"Inserted Text Before Delimiter", "Text Before Delimiter.1", each Text.BeforeDelimiter([Text Before Delimiter], " "), type text), #"Changed Type3" = Table.TransformColumnTypes(#"Inserted Text Before Delimiter1",{{"Text Before Delimiter.1", Int64.Type}}), #"Replaced Errors" = Table.ReplaceErrorValues(#"Changed Type3", {{"Text Before Delimiter.1", null}}), #"Added Custom4" = Table.AddColumn(#"Replaced Errors", "BLOCK", each let CustomColumn = if Text.Contains([Text After Delimiter], "&") then [Text After Delimiter] else let StreetName = Text.AfterDelimiter([Location], " "), BlockNumber = Number.ToText(Number.IntegerDivide([Text Before Delimiter], 100) * 100) & " Block", AbbreviatedStreetName = Text.Replace( Text.Replace( Text.Replace( Text.Replace(StreetName, "Street", "St"), "Avenue", "Ave"), "Place", "Pl"), "Way", "Way") in AbbreviatedStreetName & ", " & BlockNumber in CustomColumn), #"Removed Columns" = Table.RemoveColumns(#"Added Custom4",{"BLOCK"}), #"Renamed Columns" = Table.RenameColumns(#"Removed Columns",{{"Text Before Delimiter", "LOCATION"}, {"Text Before Delimiter.1", "St#"}}), #"Added Custom5" = Table.AddColumn(#"Renamed Columns", "BLOCK", each let CustomColumn = if Text.Contains([Location], "&") then [Location] else let StreetName = Text.AfterDelimiter([Location], " "), BlockNumber = Number.ToText(Number.IntegerDivide([#"St#"], 100) * 100) & " Block", AbbreviatedStreetName = Text.Replace( Text.Replace( Text.Replace( Text.Replace(StreetName, "Street", "St"), "Avenue", "Ave"), "Place", "Pl"), "Way", "Way") in AbbreviatedStreetName & ", " & BlockNumber in CustomColumn), #"Renamed Columns1" = Table.RenameColumns(#"Added Custom5",{{"LOCATION", "Location"}}), #"Removed Columns1" = Table.RemoveColumns(#"Renamed Columns1",{"BLOCK"}), BLOCK = Table.AddColumn(#"Removed Columns1", "BLOCK", each let CustomColumn = if Text.Contains([Location], "&") then [Location] else let StreetName = Text.AfterDelimiter([Location], " "), BlockNumber = Number.ToText(Number.IntegerDivide([#"St#"], 100) * 100) & " Block", AbbreviatedStreetName = Text.Replace( Text.Replace( Text.Replace( Text.Replace(StreetName, "Street", "St"), "Avenue", "Ave"), "Place", "Pl"), "Way", "Way") in AbbreviatedStreetName & ", " & BlockNumber in CustomColumn), TIME_OF_DAY = Table.AddColumn(BLOCK, "TIME_OF_DAY", each if [Start of Hour] >= #time(0, 0, 0) and [Start of Hour] < #time(4, 0, 0) then "Early Morning (00:00-03:59)" else if [Start of Hour] >= #time(4, 0, 0) and [Start of Hour] < #time(8, 0, 0) then "Morning (04:00-07:59)" else if [Start of Hour] >= #time(8, 0, 0) and [Start of Hour] < #time(12, 0, 0) then "Morning Peak (08:00-11:59)" else if [Start of Hour] >= #time(12, 0, 0) and [Start of Hour] < #time(16, 0, 0) then "Afternoon (12:00-15:59)" else if [Start of Hour] >= #time(16, 0, 0) and [Start of Hour] < #time(20, 0, 0) then "Evening Peak (16:00-19:59)" else "Night (20:00-23:59)"), #"Trimmed Text1" = Table.TransformColumns(TIME_OF_DAY,{{"Narrative", Text.Trim, type text}}), #"Cleaned Text1" = Table.TransformColumns(#"Trimmed Text1",{{"Narrative", Text.Clean, type text}}), #"Changed Type4" = Table.TransformColumnTypes(#"Cleaned Text1",{{"Total Value Stolen", Currency.Type}, {"Total Value Recover", Currency.Type}}), #"Trimmed Text2" = Table.TransformColumns(Table.TransformColumnTypes(#"Changed Type4", {{"Model2", type text}, {"Make2", type text}, {"Reg State 2", type text}, {"Registration 2", type text}}, "en-US"),{{"Reg State 1", Text.Trim, type text}, {"Model1", Text.Trim, type text}, {"Registration 1", Text.Trim, type text}, {"Make1", Text.Trim, type text}}), #"Cleaned Text2" = Table.TransformColumns(#"Trimmed Text2",{{"Reg State 1", Text.Clean, type text}, {"Model1", Text.Clean, type text}, {"Registration 1", Text.Clean, type text}, {"Make1", Text.Clean, type text}, {"Registration 2", Text.Clean, type text}, {"Reg State 2", Text.Clean, type text}, {"Model2", Text.Clean, type text}, {"Make2", Text.Clean, type text}}), #"Uppercased Text" = Table.TransformColumns(#"Cleaned Text2",{{"Reg State 1", Text.Upper, type text}, {"Model1", Text.Upper, type text}, {"Registration 1", Text.Upper, type text}, {"Make1", Text.Upper, type text}, {"Registration 2", Text.Upper, type text}, {"Reg State 2", Text.Upper, type text}, {"Model2", Text.Upper, type text}, {"Make2", Text.Upper, type text}}), #"Capitalized Each Word" = Table.TransformColumns(#"Uppercased Text",{{"Reviewed By", Text.Proper, type text}}), #"Added Custom6" = Table.AddColumn(#"Capitalized Each Word", "VEHICLE1", each if [Reg State 1] <> null and [Registration 1] <> null and [Make1] <> null and [Model1] <> null then [Reg State 1] & "-" & [Registration 1] & " " & [Make1] & ", " & [Model1] else if [Reg State 1] <> null and [Registration 1] <> null then [Reg State 1] & "-" & [Registration 1] else if [Make1] <> null and [Model1] <> null then [Make1] & ", " & [Model1] else null), #"Added Custom7" = Table.AddColumn(#"Added Custom6", "VEHICLE2", each let Combined1 = if [Reg State 1] <> null and [Registration 1] <> null and [Make1] <> null and [Model1] <> null then "Vehicle 1: " & [Reg State 1] & "-" & [Registration 1] & " " & [Make1] & ", " & [Model1] else if [Reg State 1] <> null and [Registration 1] <> null then "Vehicle 1: " & [Reg State 1] & "-" & [Registration 1] else if [Make1] <> null and [Model1] <> null then "Vehicle 1: " & [Make1] & ", " & [Model1] else null,
Combined2 = if [Reg State 2] <> null and [Registration 2] <> null and [Make2] <> null and [Model2] <> null then
                "Vehicle 2: " & [Reg State 2] & "-" & [Registration 2] & " " & [Make2] & ", " & [Model2]
            else if [Reg State 2] <> null and [Registration 2] <> null then
                "Vehicle 2: " & [Reg State 2] & "-" & [Registration 2]
            else if [Make2] <> null and [Model2] <> null then
                "Vehicle 2: " & [Make2] & ", " & [Model2]
            else
                null,

Result = if Combined1 <> null and Combined2 <> null then
             Combined1 & " | " & Combined2
         else if Combined1 <> null then
             Combined1
         else
             Combined2
 
in Result), #"Removed Columns2" = Table.RemoveColumns(#"Added Custom7",{"VEHICLE1"}), #"Renamed Columns2" = Table.RenameColumns(#"Removed Columns2",{{"VEHICLE2", "VEHICLE"}}), #"Duplicated Column" = Table.DuplicateColumn(#"Renamed Columns2", "Narrative", "Narrative - Copy"), #"Added Custom8" = Table.AddColumn(#"Duplicated Column", "Custom", each let text = [Narrative], lowerText = Text.Lower(text), splitBySuspect = Text.Split(lowerText, "suspect"), extractList = List.Transform(List.RemoveFirstN(splitBySuspect, 1), each "suspect" & Text.BeforeDelimiter(, ". ")), combinedText = Text.Combine(extractList, " ") in combinedText), #"Renamed Columns3" = Table.RenameColumns(#"Added Custom8",{{"Custom", "Suspect"}}), #"Reordered Columns5" = Table.ReorderColumns(#"Renamed Columns3",{"Case Number", "INC_DATE", "Month Name", "Day Name", "INC_TIME", "Start of Hour", "Incident Type_1", "ALL_INCIDENTS", "Incident Type_2", "Incident Type_3", "FullAddress", "Grid", "Zone", "Narrative", "Total Value Stolen", "Total Value Recover", "Registration 1", "Make1", "Model1", "Reg State 1", "Registration 2", "Reg State 2", "Make2", "Model2", "Reviewed By", "CompleteCalc", "Officer of Record", "Squad", "Det_Assigned", "Case_Status", "NIBRS Classification", "CASE_NUMBER_LENGTH", "Incident Date", "Incident Time", "Incident Date_Between", "Incident Time_Between", "Report Date", "Report Time", "Year", "Week of Year", "Week of Month", "Day", "Day of Year", "INC_DATE_AND_TIME", "Location", "St#", "BLOCK", "TIME_OF_DAY", "VEHICLE", "Suspect", "Narrative - Copy"}), #"Added Custom9" = Table.AddColumn(#"Reordered Columns5", "Amount Taken", each let text = [Narrative], splitByDollar = Text.Split(text, "$"), extractList = List.Transform(List.RemoveFirstN(splitByDollar, 1), each try "$" & Text.BeforeDelimiter(, ". ", 2) otherwise ""), combinedText = Text.Combine(List.Select(extractList, each _ <> ""), " ") in combinedText), #"Reordered Columns6" = Table.ReorderColumns(#"Added Custom9",{"Case Number", "INC_DATE", "Month Name", "Day Name", "INC_TIME", "Start of Hour", "Incident Type_1", "ALL_INCIDENTS", "Incident Type_2", "Incident Type_3", "FullAddress", "Grid", "Zone", "Narrative", "Total Value Stolen", "Total Value Recover", "Registration 1", "Make1", "Model1", "Reg State 1", "Registration 2", "Reg State 2", "Make2", "Model2", "Reviewed By", "CompleteCalc", "Officer of Record", "Squad", "Det_Assigned", "Case_Status", "NIBRS Classification", "CASE_NUMBER_LENGTH", "Incident Date", "Incident Time", "Incident Date_Between", "Incident Time_Between", "Report Date", "Report Time", "Year", "Week of Year", "Week of Month", "Day", "Day of Year", "INC_DATE_AND_TIME", "Location", "St#", "BLOCK", "TIME_OF_DAY", "VEHICLE", "Suspect", "Amount Taken", "Narrative - Copy"}), #"Renamed Columns4" = Table.RenameColumns(#"Reordered Columns6",{{"Amount Taken", "TOTAL_STOLEN_AMOUNT"}}), #"Trimmed Text3" = Table.TransformColumns(#"Renamed Columns4",{{"Suspect", Text.Trim, type text}}), #"Cleaned Text3" = Table.TransformColumns(#"Trimmed Text3",{{"Suspect", Text.Clean, type text}}), #"Reordered Columns7" = Table.ReorderColumns(#"Cleaned Text3",{"Case Number", "Start of Hour", "INC_TIME", "Day Name", "Month Name", "INC_DATE", "Location", "Incident Type_1", "ALL_INCIDENTS", "Incident Type_2", "Incident Type_3", "FullAddress", "Grid", "Zone", "Narrative", "Total Value Stolen", "Total Value Recover", "Registration 1", "Make1", "Model1", "Reg State 1", "Registration 2", "Reg State 2", "Make2", "Model2", "Reviewed By", "CompleteCalc", "Officer of Record", "Squad", "Det_Assigned", "Case_Status", "NIBRS Classification", "CASE_NUMBER_LENGTH", "Incident Date", "Incident Time", "Incident Date_Between", "Incident Time_Between", "Report Date", "Report Time", "Year", "Week of Year", "Week of Month", "Day", "Day of Year", "INC_DATE_AND_TIME", "St#", "BLOCK", "TIME_OF_DAY", "Narrative - Copy", "VEHICLE", "Suspect", "TOTAL_STOLEN_AMOUNT"}), #"Replaced Value" = Table.ReplaceValue(#"Reordered Columns7","June","February",Replacer.ReplaceText,{"Month Name"}), #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value",#date(2017, 6, 20),#date(2025, 2, 20),Replacer.ReplaceValue,{"INC_DATE"}), #"Removed Duplicates" = Table.Distinct(#"Replaced Value1", {"Case Number"}), REPORT_CYCLE = Table.AddColumn(#"Removed Duplicates", "REPORT_CYCLE", each let // Determine Cycle with Leading Zeros Cycle = if [INC_DATE] >= #date(2024, 12, 31) and [INC_DATE] <= #date(2025, 1, 27) then "C01" else if [INC_DATE] >= #date(2025, 1, 28) and [INC_DATE] <= #date(2025, 2, 24) then "C02" else if [INC_DATE] >= #date(2025, 2, 25) and [INC_DATE] <= #date(2025, 3, 24) then "C03" else if [INC_DATE] >= #date(2025, 3, 25) and [INC_DATE] <= #date(2025, 4, 21) then "C04" else if [INC_DATE] >= #date(2025, 4, 22) and [INC_DATE] <= #date(2025, 5, 19) then "C05" else if [INC_DATE] >= #date(2025, 5, 20) and [INC_DATE] <= #date(2025, 6, 16) then "C06" else if [INC_DATE] >= #date(2025, 6, 17) and [INC_DATE] <= #date(2025, 7, 14) then "C07" else if [INC_DATE] >= #date(2025, 7, 15) and [INC_DATE] <= #date(2025, 8, 11) then "C08" else if [INC_DATE] >= #date(2025, 8, 12) and [INC_DATE] <= #date(2025, 9, 8) then "C09" else if [INC_DATE] >= #date(2025, 9, 9) and [INC_DATE] <= #date(2025, 10, 6) then "C10" else if [INC_DATE] >= #date(2025, 10, 7) and [INC_DATE] <= #date(2025, 11, 3) then "C11" else if [INC_DATE] >= #date(2025, 11, 4) and [INC_DATE] <= #date(2025, 12, 1) then "C12" else if [INC_DATE] >= #date(2025, 12, 2) and [INC_DATE] <= #date(2025, 12, 29) then "C13" else if [INC_DATE] >= #date(2025, 12, 30) and [INC_DATE] <= #date(2026, 1, 26) then "C14" else null,
// Determine Week with Leading Zeros
Week = 
    let
        WeekNumber = 
            if [INC_DATE] >= #date(2024, 12, 31) and [INC_DATE] <= #date(2025, 1, 6) then 1
            else if [INC_DATE] >= #date(2025, 1, 7) and [INC_DATE] <= #date(2025, 1, 13) then 2
            else if [INC_DATE] >= #date(2025, 1, 14) and [INC_DATE] <= #date(2025, 1, 20) then 3
            else if [INC_DATE] >= #date(2025, 1, 21) and [INC_DATE] <= #date(2025, 1, 27) then 4
            else if [INC_DATE] >= #date(2025, 1, 28) and [INC_DATE] <= #date(2025, 2, 3) then 5
            else if [INC_DATE] >= #date(2025, 2, 4) and [INC_DATE] <= #date(2025, 2, 10) then 6
            else if [INC_DATE] >= #date(2025, 2, 11) and [INC_DATE] <= #date(2025, 2, 17) then 7
            else if [INC_DATE] >= #date(2025, 2, 18) and [INC_DATE] <= #date(2025, 2, 24) then 8
            else if [INC_DATE] >= #date(2025, 2, 25) and [INC_DATE] <= #date(2025, 3, 3) then 9
            else if [INC_DATE] >= #date(2025, 3, 4) and [INC_DATE] <= #date(2025, 3, 10) then 10
            else if [INC_DATE] >= #date(2025, 3, 11) and [INC_DATE] <= #date(2025, 3, 17) then 11
            else if [INC_DATE] >= #date(2025, 3, 18) and [INC_DATE] <= #date(2025, 3, 24) then 12
            else if [INC_DATE] >= #date(2025, 3, 25) and [INC_DATE] <= #date(2025, 3, 31) then 13
            else if [INC_DATE] >= #date(2025, 4, 1) and [INC_DATE] <= #date(2025, 4, 7) then 14
            else if [INC_DATE] >= #date(2025, 4, 8) and [INC_DATE] <= #date(2025, 4, 14) then 15
            else if [INC_DATE] >= #date(2025, 4, 15) and [INC_DATE] <= #date(2025, 4, 21) then 16
            else if [INC_DATE] >= #date(2025, 4, 22) and [INC_DATE] <= #date(2025, 4, 28) then 17
            else if [INC_DATE] >= #date(2025, 4, 29) and [INC_DATE] <= #date(2025, 5, 5) then 18
            else if [INC_DATE] >= #date(2025, 5, 6) and [INC_DATE] <= #date(2025, 5, 12) then 19
            else if [INC_DATE] >= #date(2025, 5, 13) and [INC_DATE] <= #date(2025, 5, 19) then 20
            else if [INC_DATE] >= #date(2025, 5, 20) and [INC_DATE] <= #date(2025, 5, 26) then 21
            else if [INC_DATE] >= #date(2025, 5, 27) and [INC_DATE] <= #date(2025, 6, 2) then 22
            else if [INC_DATE] >= #date(2025, 6, 3) and [INC_DATE] <= #date(2025, 6, 9) then 23
            else if [INC_DATE] >= #date(2025, 6, 10) and [INC_DATE] <= #date(2025, 6, 16) then 24
            else if [INC_DATE] >= #date(2025, 6, 17) and [INC_DATE] <= #date(2025, 6, 23) then 25
            else if [INC_DATE] >= #date(2025, 6, 24) and [INC_DATE] <= #date(2025, 6, 30) then 26
            else null,

        // Format Week Number as W##
        WeekFormatted = if WeekNumber <> null then "W" & Text.PadStart(Text.From(WeekNumber), 2, "0") else null
    in
        WeekFormatted,

// Combine Cycle and Week into C##W##
Result = if Cycle <> null and Week <> null then Cycle & Week else null
 
in Result), #"Reordered Columns8" = Table.ReorderColumns(REPORT_CYCLE,{"Case Number", "INC_DATE", "Start of Hour", "TIME_OF_DAY", "INC_TIME", "Day Name", "Month Name", "BLOCK", "Location", "Incident Type_1", "ALL_INCIDENTS", "Incident Type_2", "Incident Type_3", "FullAddress", "Grid", "Zone", "Narrative", "Total Value Stolen", "Total Value Recover", "Registration 1", "Make1", "Model1", "Reg State 1", "Registration 2", "Reg State 2", "Make2", "Model2", "Reviewed By", "CompleteCalc", "Officer of Record", "Squad", "Det_Assigned", "Case_Status", "NIBRS Classification", "CASE_NUMBER_LENGTH", "Incident Date", "Incident Time", "Incident Date_Between", "Incident Time_Between", "Report Date", "Report Time", "Year", "Week of Year", "Week of Month", "Day", "Day of Year", "INC_DATE_AND_TIME", "St#", "Narrative - Copy", "VEHICLE", "Suspect", "TOTAL_STOLEN_AMOUNT", "REPORT_CYCLE"}), #"Added Custom11" = Table.AddColumn(#"Reordered Columns8", "Custom", each if [Start of Hour] >= #time(0, 0, 0) and [Start of Hour] < #time(4, 0, 0) then "00:00-03:59 Early Morning" else if [Start of Hour] >= #time(4, 0, 0) and [Start of Hour] < #time(8, 0, 0) then "04:00-07:59 Morning" else if [Start of Hour] >= #time(8, 0, 0) and [Start of Hour] < #time(12, 0, 0) then "08:00-11:59 Morning Peak" else if [Start of Hour] >= #time(12, 0, 0) and [Start of Hour] < #time(16, 0, 0) then "12:00-15:59 Afternoon" else if [Start of Hour] >= #time(16, 0, 0) and [Start of Hour] < #time(20, 0, 0) then "16:00-19:59 Evening Peak" else "20:00-23:59 Night"), #"Renamed Columns5" = Table.RenameColumns(#"Added Custom11",{{"Custom", "TOD"}}), #"Reordered Columns9" = Table.ReorderColumns(#"Renamed Columns5",{"Case Number", "INC_DATE", "TOD", "Start of Hour", "INC_TIME", "Day Name", "Month Name", "BLOCK", "Location", "Incident Type_1", "ALL_INCIDENTS", "Incident Type_2", "Incident Type_3", "FullAddress", "Grid", "Zone", "Narrative", "Total Value Stolen", "Total Value Recover", "Registration 1", "Make1", "Model1", "Reg State 1", "Registration 2", "Reg State 2", "Make2", "Model2", "Reviewed By", "CompleteCalc", "Officer of Record", "Squad", "Det_Assigned", "Case_Status", "NIBRS Classification", "CASE_NUMBER_LENGTH", "Incident Date", "Incident Time", "Incident Date_Between", "Incident Time_Between", "Report Date", "Report Time", "Year", "Week of Year", "Week of Month", "Day", "Day of Year", "INC_DATE_AND_TIME", "St#", "Narrative - Copy", "VEHICLE", "Suspect", "TOTAL_STOLEN_AMOUNT", "REPORT_CYCLE", "TIME_OF_DAY"}), #"Sorted Rows" = Table.Sort(#"Reordered Columns9",{{"INC_DATE", Order.Descending}}), #"Renamed Columns6" = Table.RenameColumns(#"Sorted Rows",{{"Narrative - Copy", "Notes"}}), #"Sorted Rows1" = Table.Sort(#"Renamed Columns6",{{"INC_DATE", Order.Ascending}}), #"Replaced Value2" = Table.ReplaceValue(#"Sorted Rows1","Friday","Fri",Replacer.ReplaceText,{"Day Name"}), #"Replaced Value3" = Table.ReplaceValue(#"Replaced Value2","Monday","Mon",Replacer.ReplaceText,{"Day Name"}), #"Replaced Value4" = Table.ReplaceValue(#"Replaced Value3","Tuesday","Tue",Replacer.ReplaceText,{"Day Name"}), #"Replaced Value5" = Table.ReplaceValue(#"Replaced Value4","Wednesday","Wed",Replacer.ReplaceText,{"Day Name"}), #"Replaced Value6" = Table.ReplaceValue(#"Replaced Value5","Thursday","Thur",Replacer.ReplaceText,{"Day Name"}), #"Replaced Value7" = Table.ReplaceValue(#"Replaced Value6","Sunday","Sun",Replacer.ReplaceText,{"Day Name"}), #"Replaced Value8" = Table.ReplaceValue(#"Replaced Value7","Saturday","Sat",Replacer.ReplaceText,{"Day Name"}), #"Reordered Columns10" = Table.ReorderColumns(#"Replaced Value8",{"Case Number", "BLOCK", "Location", "ALL_INCIDENTS", "Incident Type_1", "Incident Type_2", "Incident Type_3", "FullAddress", "Grid", "Zone", "Narrative", "Total Value Stolen", "Total Value Recover", "Registration 1", "Make1", "Model1", "Reg State 1", "Registration 2", "Reg State 2", "Make2", "Model2", "Reviewed By", "CompleteCalc", "Officer of Record", "Squad", "Det_Assigned", "Case_Status", "NIBRS Classification", "CASE_NUMBER_LENGTH", "Incident Date", "Incident Time", "Incident Date_Between", "Incident Time_Between", "Report Date", "Report Time", "Year", "St#", "Notes", "VEHICLE", "Suspect", "TOTAL_STOLEN_AMOUNT", "INC_DATE", "TOD", "Start of Hour", "INC_TIME", "Day Name", "Month Name", "Week of Year", "Week of Month", "Day", "Day of Year", "INC_DATE_AND_TIME", "TIME_OF_DAY", "REPORT_CYCLE"}) in #"Reordered Columns10"
Grok Updated M Code
let
    // Use Folder.Files for dynamic file loading (Issue 9)
    Source = try Folder.Files("C:\Path\To\Folder") otherwise error "Invalid folder path",
    // Combine all Excel files in the folder
    CombinedFiles = Table.Combine(
        Table.TransformRows(Source, each 
            let
                Workbook = Excel.Workbook([Content], null, true),
                Sheet = Workbook{[Item="Sheet1", Kind="Sheet"]}[Data]
            in
                Sheet
        )
    ),
    #"Promoted Headers" = Table.PromoteHeaders(CombinedFiles, [PromoteAllScalars=true]),
    // Validate Case Number length
    #"Added Custom" = Table.AddColumn(#"Promoted Headers", "CASE_NUMBER_LENGTH", each Text.Length([Case Number]??"") ),
    #"Filtered Rows" = Table.SelectRows(#"Added Custom", each [CASE_NUMBER_LENGTH] = 9),
    // Set data types for date/time columns
    #"Changed Type" = Table.TransformColumnTypes(#"Filtered Rows", {
        {"Incident Date", type date}, 
        {"Incident Date_Between", type date}, 
        {"Report Date", type date}, 
        {"Report Time", type time}, 
        {"Incident Time_Between", type time}, 
        {"Incident Time", type time}
    }, "en-US"),
    // Calculate INC_DATE with null handling (Issue 5)
    #"Added Custom1" = Table.AddColumn(#"Changed Type", "INC_DATE", each 
        if [Incident Date] <> null then [Incident Date]
        else if [Incident Date_Between] <> null then [Incident Date_Between]
        else if [Report Date] <> null then [Report Date]
        else null, type date),
    // Calculate INC_TIME with null handling
    #"Added Custom2" = Table.AddColumn(#"Added Custom1", "INC_TIME", each 
        if [Incident Time] <> null then [Incident Time]
        else if [Incident Time_Between] <> null then [Incident Time_Between]
        else if [Report Time] <> null then [Report Time]
        else null, type time),
    // Set data types for new columns
    #"Changed Type1" = Table.TransformColumnTypes(#"Added Custom2", {{"INC_DATE", type date}, {"INC_TIME", type time}}),
    // Calculate Start of Hour
    #"Inserted Start of Hour" = Table.AddColumn(#"Changed Type1", "Start of Hour", each Time.StartOfHour([INC_TIME]?? "00:00:00"), type time),
    // Extract date components
    #"Inserted Year" = Table.AddColumn(#"Inserted Start of Hour", "Year", each Date.Year([INC_DATE]? ?#date(2025,1,1)), Int64.Type),
    #"Inserted Month Name" = Table.AddColumn(#"Inserted Year", "Month Name", each Date.MonthName([INC_DATE]? ?#date(2025,1,1)), type text),
    #"Inserted Week of Year" = Table.AddColumn(#"Inserted Month Name", "Week of Year", each Date.WeekOfYear([INC_DATE]? ?#date(2025,1,1)), Int64.Type),
    #"Inserted Week of Month" = Table.AddColumn(#"Inserted Week of Year", "Week of Month", each Date.WeekOfMonth([INC_DATE]? ?#date(2025,1,1)), Int64.Type),
    #"Inserted Day" = Table.AddColumn(#"Inserted Week of Month", "Day", each Date.Day([INC_DATE]? ?#date(2025,1,1)), Int64.Type),
    #"Inserted Day of Year" = Table.AddColumn(#"Inserted Day", "Day of Year", each Date.DayOfYear([INC_DATE]? ?#date(2025,1,1)), Int64.Type),
    #"Inserted Day Name" = Table.AddColumn(#"Inserted Day of Year", "Day Name", each Date.DayOfWeekName([INC_DATE]? ?#date(2025,1,1)), type text),
    // Combine date and time
    #"Inserted Merged Column" = Table.AddColumn(#"Inserted Day Name", "INC_DATE_AND_TIME", each 
        if [INC_DATE] <> null and [INC_TIME] <> null then 
            Text.Combine({Text.From([INC_DATE], "en-US"), Text.From([INC_TIME], "en-US")}, " ")
        else null, type text),
    #"Changed Type2" = Table.TransformColumnTypes(#"Inserted Merged Column", {{"INC_DATE_AND_TIME", type datetime}}),
    // Clean Incident Type columns (Issue 4)
    #"Extracted Text Before Delimiter" = Table.TransformColumns(#"Changed Type2", {
        {"Incident Type_1", each Text.BeforeDelimiter(_?? "", " - 2C:"), type text},
        {"Incident Type_2", each Text.BeforeDelimiter(_?? "", " - 2C:"), type text},
        {"Incident Type_3", each Text.BeforeDelimiter(_??